# https://docs.microsoft.com/azure/devops/pipelines/languages/java
# with inspiration from https://github.com/quarkusio/quarkus/blob/master/azure-pipelines.yml
trigger:
  batch: true
  branches:
    include:
    - master
  tags:
    include:
      - 0.*

pr:
  branches:
    include:
    - master

jobs:
 - job: Check
   timeoutInMinutes: 10
   pool:
     vmImage: 'ubuntu-16.04'
   
   steps:
   - task: Gradle@2
     displayName: 'Run tests and build release'
     inputs:
       jdkVersionOption: '1.11'
       tasks: 'release'
       
   - publish: $(System.DefaultWorkingDirectory)/dist
     artifact: Backup
     condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
  