# https://docs.microsoft.com/azure/devops/pipelines/languages/java
# with inspiration from https://github.com/quarkusio/quarkus/blob/master/azure-pipelines.yml
trigger:
  batch: true
  tags:
    include:
      - 0.*
      - 1.*

pr:
  branches:
    include:
    - master

jobs:
 - job: Check
   timeoutInMinutes: 10
   pool:
     vmImage: 'ubuntu-16.04'
   
   steps:
   - task: Gradle@2
     displayName: 'Run tests and build release'
     inputs:
       jdkVersionOption: '1.11'
       tasks: 'release'
       publishJUnitResults: false
   - task: PublishTestResults@2
     inputs:
       testResultsFormat: 'JUnit'
       failTaskOnFailedTests: true 
       publishRunAttachments: true
   
       
       
   - task: GitHubRelease@0
     condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
     inputs:
       gitHubConnection: 'GitHub Release'
       action: 'edit'
       assets: $(System.DefaultWorkingDirectory)/dist/*
       tag: $(Build.SourceBranchName)
       
  